name: loyinle
description: "app parcours des geants"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.1.2
  intl: ^0.19.0
  get_time_ago: ^1.3.1
  wakelock: ^0.6.2

  path: ^1.8.3
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  get_storage: ^2.0.3
  provider: ^6.0.2
  lottie: ^3.0.0
  talker: ^3.2.0
  video_player: ^2.6.1
  gif_view: ^0.4.0
  belatuk_http_server: ^4.2.0
  flutter_phoenix:
  slide_countdown: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
  fonts:
    - family: Baloo
      fonts:
        - asset: third_party/Baloo-Regular.ttf
    - family: Power Grotesk
      fonts:
        - asset: assets/fonts/PowerGrotesk-Regular.ttf
        - asset: assets/fonts/PowerGrotesk-Black.ttf
        - asset: assets/fonts/PowerGrotesk-BlackItalic.ttf
        - asset: assets/fonts/PowerGrotesk-Bold.ttf
        - asset: assets/fonts/PowerGrotesk-BoldItalic.ttf
        - asset: assets/fonts/PowerGrotesk-Heavy.ttf
        - asset: assets/fonts/PowerGrotesk-HeavyItalic.ttf
        - asset: assets/fonts/PowerGrotesk-Light.ttf
        - asset: assets/fonts/PowerGrotesk-LightItalic.ttf
        - asset: assets/fonts/PowerGrotesk-Medium.ttf
        - asset: assets/fonts/PowerGrotesk-MediumItalic.ttf
        - asset: assets/fonts/PowerGrotesk-Regular.ttf
        - asset: assets/fonts/PowerGrotesk-UltraBold.ttf
        - asset: assets/fonts/PowerGrotesk-UltraBoldItalic.ttf
        - asset: assets/fonts/PowerGrotesk-UltraLight.ttf
        - asset: assets/fonts/PowerGrotesk-UltraLightItalic.ttf


    - family: Power Grotesk Reg
      fonts:
        - asset: assets/fonts/PowerGrotesk-Regular.ttf

    - family: Power Grotesk Bold
      fonts:
        - asset: assets/fonts/PowerGrotesk-Bold.ttf